baseURL = "https://araboud.ca/"
languageCode = "en-us"
title = "araboud.ca"
theme = "ananke"

[markup.goldmark.renderer]
unsafe= true

[params]
  background_color_class = "araboud-bg"
  site_logo = "/imgs/ar_logo.png"
  custom_css = [ "/css/main.css" ]

linkedin = "https://www.linkedin.com/in/alex-raboud/"
github = "https://www.github.com/ataboo"

[menu]
  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 10

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 20
