name: CI
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme submodule
        run: git submodule update --init --recursive themes/ananke

      - name: Checkout dist repo
        uses: actions/checkout@v2
        with:
          repository: 'ataboo/araboud.ca_dist'
          token: '${{secrets.DIST_REPO_TOKEN}}'
          path: 'cloned_dist'

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
      
      - name: Build hugo
        run: hugo --minify -d ./cloned_dist
      
      - name: Commit to dist submodule
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Alex Raboud (CI)
          author_email: doubar2001@gmail.com
          cwd: './cloned_dist'
          message: 'Built by Github Actions'
          force: true
env:
  GITHUB_TOKEN: ${{secrets.DIST_REPO_TOKEN}}

