name: CI
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Build and FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
      
      - name: Build hugo
        run: hugo --minify -d ./araboud.ca_dist
      
      - name: Commit to dist submodule
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Alex Raboud (CI)
          author_email: doubar2001@gmail.com
          cwd: './araboud.ca_dist'
          message: 'Built by Github Actions'
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

